services:
  mongodb:
    container_name: mongodb
    #image: mongo:latest
    image: mongo:4.4.29 # This is due to limitations in the Virtual Wall's hardware
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    # Don't attach a volume, as we do not want the data to persist between benchmark runs
    #volumes:
    #  - ./mongo-data:/data/db
    # Don't expose the port to the outside world when running publicly
    #ports:
    #  - 27017:27017
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - ldes
  ldes-server:
    container_name: ldes-server
    build: ./ldes-server
    restart: always
    command: -b http://localhost:3000
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - ldes
    depends_on:
      - mongodb
  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: always
    ports:
      - 3000:80
    volumes:
      - ${NGINX_CONFIG:-./nginx/configs/default.conf}:/etc/nginx/nginx.conf
      - ./nginx/ldes-server.conf:/etc/nginx/conf.d/default.conf
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - ldes
    depends_on:
      ldes-server:
        condition: service_healthy
  ingest-server:
    container_name: ingest-server
    build: ./ingest-server
    entrypoint: [ "npx", "js-runner", "${INGEST_PIPELINE:-pipeline.ttl}" ]
    environment:
      # - DEBUG=*
      - INTERVAL=${INTERVAL}
      - AMOUNT_PER_INTERVAL=${AMOUNT_PER_INTERVAL}
      - PAGE_SIZE=${PAGE_SIZE}
    volumes:
      - ./setup/replication-data.txt:/opt/pipeline/data/replication-data.txt
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - ldes
    depends_on:
      ldes-server:
        condition: service_healthy
      nginx:
        condition: service_started

networks:
  ldes:
    name: ldes-network
