services:
  mongodb:
    container_name: mongodb
    #image: mongo:latest
    image: mongo:4.4.29 # This is due to limitations in the Virtual Wall's hardware
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    # Don't attach a volume, as we do not want the data to persist between benchmark runs
    #volumes:
    #  - ./mongo-data:/data/db
    # Don't expose the port to the outside world when running publicly
    ports:
      - 27017:27017
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - ldes
  redis:
    container_name: redis
    image: redis/redis-stack-server:latest
    # Don't attach a volume, as we do not want the data to persist between benchmark runs
    #volumes:
    #  - ./redis-data:/data
    # Don't expose the port to the outside world when running publicly
    ports:
      - 6379:6379
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - ldes
  ldes-server:
    container_name: ldes-server
    build: https://raw.githubusercontent.com/smessie/ldes-evaluation-runner/refs/heads/main/ldes-server/Dockerfile
    restart: always
    command: -b http://${SERVER_HOSTNAME:-localhost}:3000
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SERVER_HOSTNAME=${SERVER_HOSTNAME:-localhost}
    healthcheck:
      test: "wget --server-response --spider --tries=1 http://localhost:3000 2>&1 | grep -E 'HTTP/1.1 (200|500)'"  # Check if the server is up and running, can return 200 or 500 (outside identifier space, okay here)
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - ldes
    depends_on:
      - mongodb
  nginx:
    container_name: nginx
    image: fholzer/nginx-brotli:v1.26.2
    restart: always
    ports:
      - 3000:80
    volumes:
      - ${NGINX_CONFIG:-./nginx/configs/default.conf}:/etc/nginx/nginx.conf
      - ${NGINX_SITE:-./nginx/ldes-server.conf}:/etc/nginx/conf.d/default.conf
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - ldes
    depends_on:
      ldes-server:
        condition: service_healthy
  ingest-server:
    container_name: ingest-server
    build: https://raw.githubusercontent.com/smessie/ldes-evaluation-runner/refs/heads/main/ingest-server/Dockerfile
    entrypoint: [ "npx", "js-runner", "${INGEST_PIPELINE:-pipeline.ttl}" ]
    environment:
      # - DEBUG=*
      - INTERVAL=${INTERVAL}
      - AMOUNT_PER_INTERVAL=${AMOUNT_PER_INTERVAL}
      - PAGE_SIZE=${PAGE_SIZE}
      - DATABASE_URL=${DATABASE_URL}
      - METADATA_FILE=${METADATA_FILE}
      - UNORDERED_RELATIONS=${UNORDERED_RELATIONS}
      - SERVER_HOSTNAME=${SERVER_HOSTNAME:-localhost}
    volumes:
      - ${REPLICATION_DATA:-./setup/replication-data.txt}:/opt/pipeline/data/replication-data.txt
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - ldes
    depends_on:
      ldes-server:
        condition: service_healthy
      nginx:
        condition: service_started

networks:
  ldes:
    name: ldes-network
